# Definir a Imagem (neste caso Imagem do nginx):
FROM nginx

# Copiar o arquivo para dentro da nginx (usr/share/nginx/html documentação):
COPY ./index.html /usr/share/nginx/html

# Para mostrar em qual porta nossa aplicação irá rodar:
EXPOSE 3000

# Variáveis de ambientes (Para utilizar dentro dos nossos container):
ENV API_URL=http://localhost:8000/api/

# Definir a pasta de trabalho da nossa imagem (A pasta que será direcionada quando acessar nosso container):
WORKDIR /usr/share/nginx/html

# Comando que permite rodar qualquer comando BASH na hora que da criação da nossa imagem:
RUN ls

# CMD e ENTRYPOINT: Define o que será executado ao subir o nosso container (docker container run)
# ENTRYPOINT: Serve para definir qual o executável nosso container irá usar
# CMD: Serve para nos configurarmos os parametros que serão enviados para esse executavel
ENTRYPOINT [ "/usr/sbin/nginx" ]
CMD [ "-g", "daemon off;" ]

# para buildar execute o comando: docker build .
