version: '3'
services:
  todoback:
    container_name: backend
    build: ./back-end
    ports:
      - "3001:3001"
  todofront:
    container_name: frontend
    build: ./front-end
    ports:
      - "3000:3000"
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
  todotests:
    container_name: tests
    build: ./tests
    depends_on:
      - todofront
    environment:
      - FRONT_HOST=todofront
