const movies = [
  {
    title: 'Ninja Clash In The Land Of Snow',
    subtitle: 'After episode 101 (Classic Naruto)',
    storyline: "",
    year: 2004,
    rating: 10.0,
    imagePath: 'img/Ninja_Clash_In_The_Land_Of_Snow.png'
  },
  {
    title: 'Legend Of The Stone Of Gelel',
    subtitle: 'Follows episode 160 (Classic Naruto)',
    storyline: "Team 7 is tasked with protecting the Gelel Stone, a powerful mineral that can grant its user regenerative abilities and slow down aging. The powers of the stone were once controlled by a clan, but wars over its power led them to extinction.",
    year: 2005,
    rating: 10.0,
    imagePath: 'img/Legend_Of_The_Stone_Of_Gelel.jpg',
  },
  {
    title: 'Guardians Of The Crescent Moon Kingdom',
    subtitle: 'After episode 196 (Classic Naruto)',
    storyline: "Team 7 and Rock Lee are tasked with protecting Michiru, prince of the Land of the Moon, and his son Hikaru Tsuki. The team fought against Ishidate, a mercenary hired by the minister Shabadaba to kill the prince and his son.",
    rating: 10.0,
    year: 2006,
    imagePath: 'img/Guardians_Of_The_Crescent_Moon_Kingdom.png',
  },
  {
    title: 'Naruto Shippuden The Movie',
    subtitle: 'Follows episode 032 (Naruto Shippuden)',
    storyline: "When the spirit of the demon Mōryō threatens to destroy the world, Team 7 is sent to protect Sion, a priestess who would be able to seal Mōryō's spirit away again and save the world.",
    rating: 10.0,
    year: 2007,
    imagePath: 'img/Naruto_Shippuden_The_Movie.jpg',
  },
  {
    title: 'Bonds',
    subtitle: 'Follows episode 071 (Naruto Shippuden)',
    storyline: "After enemy ninjas from the Land of the Sky attack the Hidden Leaf Village as revenge for a previous attack during the 2nd Great Ninja World War, a boy named Amaru from another destroyed village comes to warn them. Naruto, Sakura, and Hinata protect the boy while trying to figure out why his village was destroyed.",
    rating: 10.0,
    year: 2008,
    imagePath: 'img/Bonds.jpg',
  },
  {
    title: 'The Will Of Fire',
    subtitle: 'Follows episode 121 (Naruto Shippuden)',
    storyline: "The plot revolves around concerns of the potential outbreak of a Fourth Great Ninja World War when the four ninjas who guard the Hidden Villages of Rock, Cloud, Mist, and Sand go missing. The team fights against Hiruko, a ninja who abandoned the Leaf Village and wants to conquer the world after plunging it into war.",
    rating: 10.0,
    year: 2009,
    imagePath: 'img/The_Will_Of_Fire.png',
  },
  {
    title: 'The Lost Tower',
    subtitle: 'Follows episode 143 (Naruto Shippuden)',
    storyline: "After Team 7 is assigned on a mission to capture a missing ninja named Mukade, Naruto and Yamato are sent 20 years into the past. The film ends with the groups memories of the experienced being erased, so it ends up having very little influence on the main storyline of the franchise.",
    rating: 10.0,
    year: 2010,
    imagePath: 'img/The_Lost_Tower.jpg',
  },
  {
    title: 'Blood Prison',
    subtitle: 'Follows episode 196 (Naruto Shippuden)',
    storyline: "The movie opens with Naruto being falsely arrested for supposedly attacking the Fourth Raikage.",
    rating: 10.0,
    year: 2011,
    imagePath: 'img/Blood_Prison.png',
  },
  {
    title: 'Road To Ninja',
    subtitle: 'After episode 251 (Naruto Shippuden)',
    storyline: "Naruto and Sakura are transported into an alternate reality by Tobi using Limited Tsukuyomi. Fans get to see what the story would be like if Naruto's parents were still alive, Sasuke never left the Hidden Leaf village, and Sakura was an orphan instead of Naruto.",
    rating: 10.0,
    year: 2012,
    imagePath: 'img/Road_To_Ninja.jpg',
  },
  {
    title: 'The Last',
    subtitle: 'After episode 493 (Naruto Shippuden)',
    storyline: "It tales place two years after the Fourth Ninja World War, and opens with the moon heading to collide with the Earth, caused by Toneri Otsutsuki, a descendant of the Sage of Six Paths' twin brother Hamura Otsutsuki.",
    rating: 10.0,
    year: 2014,
    imagePath: 'img/The_Last.jpg',
  },
  {
    title: 'Boruto - Naruto The Movie',
    subtitle: 'After episode 050 (Boruto: Naruto Next Generations)',
    storyline: "Boruto forms a team with Sarada, the daughter of Sasuke and Sakura, and Mitsuki, the son of the villain Orochimaru. After Naruto sacrifices himself to stop two villains after the Nine-Tailed spirit inside his body, Sasuke and Boruto travel to another dimension to rescue Naruto.",
    rating: 10.0,
    year: 2015,
    imagePath: 'img/Boruto_Naruto_The_Movie.jpg',
  },
];

export default movies;
