# Primeira coisa a se fazer, criar uma imagem a partir de...
FROM nginx

# O index.html deve ser passado para dentro do container (/usr/share/nginx/html=> Documentação)
COPY index.html /usr/share/nginx/html
